config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/tarun", to: "pages#tarun"
  get "/contact", to: "pages#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %I[home tarun contact]

  def home
    @markers =
      [{
        lat: 52.9381732751361652,
        lng: -1.1404715734755337,
        info_window_html: render_to_string(partial: "info_window")
      }]
  end

  def tarun
  end

  def contact
    @markers =
      [{
        lat: 52.9381732751361652,
        lng: -1.1404715734755337,
        info_window_html: render_to_string(partial: "info_window")
      }]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TarunBarber</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://kit.fontawesome.com/1d5ac3df23.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Arvo&family=Source+Code+Pro:wght@400;600&display=swap" rel="stylesheet">

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <script src="https://kit.fontawesome.com/1d5ac3df23.js" crossorigin="anonymous"></script>

  </head>
  <body>
    <header>
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>

</html>

app/views/pages/_info_window.html.erb
<h5>Get Directions</h5>
<a href="https://www.google.com/maps/dir/?api=1&destination=48%20Pyatt%20St%2C%20Nottingham%20NG2%202LF" target="_blank" class="link">Open maps</a>

app/views/pages/contact.html.erb
<div class="contact-section">
  <div class="section mt-4">
    <div class="find-grid-container">
      <div class="find-grid-item">
        <div class="service-list" id="address">
          <h3>Find Us</h3>
          <h5>Address:</h5>
          <p>48 Pyatt Street</p>
          <p>Nottingham</p>
          <p>NG2 2LF</p>
          <a href="https://www.google.com/maps/dir/?api=1&destination=48%20Pyatt%20St%2C%20Nottingham%20NG2%202LF" target="_blank" class="link mb-2">Directions <i class="fa-solid fa-arrow-up-right-from-square" style="color: #000000;"></i></a>
          <h5 class="mt-3">Email:</h5>
          <p>tarun@tarunbarber.com</p>
        </div>
      </div>

      <div class="find-grid-item">
        <div class="map-container">
          <div
            id="map"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- hero banner -->
<div class="hero">
  <div class="hero-content">
    <h1>Tarun Barber</h1>
    <p>Your Local Barber</p>
    <div class="hero-links">
      <a href="book">Book</a>
      <a href="#scroll-point">Services</a>
    </div>
  </div>
</div>

<div class="homepage-section" data-controller="showhide">
  <!-- links -->
  <div class="section-links">
    <button data-showhide-target="servicesBtn"
      data-action="click->showhide#displayServices"
      class="selected-link"
      >SERVICES
    </button>
    <button data-showhide-target="hoursBtn"
      data-action="click->showhide#displayHours"
      >OPENING HOURS
    </button>
    <button data-showhide-target="findBtn"
      data-action="click->showhide#displayFind"
      >FIND US
    </button>
    <button data-showhide-target="galleryBtn"
      data-action="click->showhide#displayGallery"
      >GALLERY
    </button>
  </div>

  <!-- services -->
  <div class="section mt-4" data-showhide-target="servicesSection" id="scroll-point">
    <div class="grid-container">
      <div class="grid-item">
        <img src="/assets/example_img" alt="" class="services-img shadow">
      </div>
      <div class="grid-item">
        <div class="service-list shadow">
          <h4>Services</h4>
          <div class="service-item">
            <p>Men's Haircut</p>
            <p>£15</p>
          </div>
          <div class="service-item">
            <p>Men's Skin fade</p>
            <p>£17</p>
          </div>
          <div class="service-item">
            <p>Men's Hair & Beard</p>
            <p>£20</p>
          </div>
          <div class="service-item">
            <p>Kid's Haircut (under 12)</p>
            <p>£12</p>
          </div>
          <div class="service-item">
            <p>Senior Haircut (over 65)</p>
            <p>£13</p>
          </div>
          <div class="service-item">
            <p>Special Cut & Beard Oils (1hr)</p>
            <p>£35</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- opening hours -->
  <div class="section d-none mt-4" data-showhide-target="hoursSection" id="scroll-point">
    <div class="grid-container">
      <div class="grid-item">
        <div class="service-list">
          <h4>Opening Hours</h4>
          <div class="service-item">
            <p>Monday</p>
            <p>10:30am - 6pm</p>
          </div>
          <div class="service-item">
            <p>Tuesday</p>
            <p>Closed</p>
          </div>
          <div class="service-item">
            <p>Wednesday - Friday</p>
            <p>9am - 6pm</p>
          </div>
          <div class="service-item">
            <p>Saturday</p>
            <p>8:30am - 3pm</p>
          </div>
          <div class="service-item">
            <p>Sunday</p>
            <p>Closed</p>
          </div>
        </div>
      </div>
      <div class="grid-item">
        <img src="/assets/example_img" alt="" class="services-img">
      </div>
    </div>
  </div>

  <!-- find us -->
  <div class="section d-none mt-4" data-showhide-target="findusSection" id="scroll-point">
    <div class="find-grid-container">
      <div class="find-grid-item">
        <div class="map-container">
          <div
            id="map"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>

      <div class="find-grid-item">
        <div class="service-list" id="address">
          <h3>Tarun Barber</h3>
          <h4>Address:</h4>
          <p>48 Pyatt Street</p>
          <p>Nottingham</p>
          <p>NG2 2LF</p>
          <a href="https://www.google.com/maps/dir/?api=1&destination=48%20Pyatt%20St%2C%20Nottingham%20NG2%202LF" target="_blank" class="link mb-2">Directions</a>
          <h4>Email:</h4>
          <p>tarun@tarunbarber.com</p>
        </div>
      </div>
    </div>
  </div>

  <!-- gallery -->
  <div class="gallery-section d-none" data-controller="gallery" data-showhide-target="gallerySection" id="scroll-point">
    <div class="full-img" data-gallery-target="fullImgBox">
      <img src="/assets/barberimg1" alt="" data-gallery-target="fullImg">
      <span data-action="click->gallery#closeFullImg">X</span>
    </div>

    <div class="img-gallery">
      <img src="/assets/barberimg1" alt="" data-action="click->gallery#open" data-src="/assets/barberimg1">
      <img src="/assets/example_img" alt="" data-action="click->gallery#open" data-src="/assets/example_img">
      <img src="/assets/barberimg1" alt="" data-action="click->gallery#open" data-src="/assets/barberimg1">
      <img src="/assets/barberimg1" alt="" data-action="click->gallery#open" data-src="/assets/barberimg1">
      <img src="/assets/barberimg1" alt="" data-action="click->gallery#open" data-src="/assets/barberimg1">
      <img src="/assets/barberimg1" alt="" data-action="click->gallery#open" data-src="/assets/barberimg1">
      <img src="/assets/barberimg1" alt="" data-action="click->gallery#open" data-src="/assets/barberimg1">
      <img src="/assets/barberimg1" alt="" data-action="click->gallery#open" data-src="/assets/barberimg1">
    </div>
  </div>
</div>

app/views/pages/tarun.html.erb
<div class="hero">
  <div class="hero-content">
    <h1>Tarun Barber</h1>
    <p>Your Local Barber</p>
    <div class="hero-links">
      <a href="book">Book</a>
      <a href="#scroll-point">About</a>
    </div>
  </div>
</div>

<div class="container">
  <h2 class="mt-5 mb-2">About</h2>
  <p id="description">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam quas accusamus dicta ullam, enim minima asperiores ipsum architecto,
    et cumque molestias quae. Magnam, eligendi ullam? Esse nulla sit debitis animi vero? Vitae adipisci natus ad delectus atque fugiat labore,
    consequuntur dolorem repellendus, eaque molestias necessitatibus consequatur sapiente aspernatur sint alias aliquid nisi, temporibus illo
    velit eveniet sed. Cumque, sint. Minima incidunt debitis laboriosam blanditiis optio, omnis neque ipsam nesciunt, modi exercitationem
    inventore rem impedit ut eaque quae necessitatibus quidem itaque, suscipit earum sunt provident a voluptas. Recusandae sit consequatur nihil
    quo minima accusantium quam? Id numquam magni ut eum eius.
  </p>

    <!-- gallery -->
  <div class="gallery-section" data-controller="gallery" id="scroll-point">
    <div class="full-img" data-gallery-target="fullImgBox">
      <img src="/assets/barberimg1" alt="" data-gallery-target="fullImg">
      <span data-action="click->gallery#closeFullImg">X</span>
    </div>

    <div class="img-gallery">
      <img src="/assets/barberimg1" alt="" data-action="click->gallery#open" data-src="/assets/barberimg1">
      <img src="/assets/example_img" alt="" data-action="click->gallery#open" data-src="/assets/example_img">
      <img src="/assets/barberimg1" alt="" data-action="click->gallery#open" data-src="/assets/barberimg1">
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navibar">
  <div class="logo">
    <a href="<%= root_path %>">Tarun Barber</a>
  </div>
  <ul class="links">
    <% if current_page?(root_path) %>
      <li><a href="tarun">Tarun</a></li>
      <li><a href="contact">Contact</a></li>
    <% elsif current_page?(tarun_path) %>
      <li><a href="<%= root_path %>">Home</a></li>
      <li><a href="contact">Contact</a></li>
    <% elsif current_page?(contact_path) %>
      <li><a href="<%= root_path %>">Home</a></li>
      <li><a href="tarun">Tarun</a></li>
    <% end %>
    <li><button id="action_btn">Book</button></li>
  </ul>
  <div class="toggle_btn">
    <i class="fa-solid fa-bars" style="color: #ffffff;"></i>
  </div>
</div>

<div class="dropdown_menu">
  <li><a href="tarun">Tarun</a></li>
  <li><a href="contact">Contact</a></li>
  <li><a href="#" id="action_btn">Book</a></li>
</div>

<script>
  const toggleBtn = document.querySelector('.toggle_btn')
  const toggleBtnIcon = document.querySelector('.toggle_btn i')
  const dropDownMenu = document.querySelector('.dropdown_menu')

  toggleBtn.onclick = function () {
    dropDownMenu.classList.toggle('open')
    const isOpen = dropDownMenu.classList.contains('open')

    toggleBtnIcon.classList = isOpen ? 'fa-solid fa-xmark' : 'fa-solid fa-bars'
  }
</script>